

CREATE TABLE `CAR`
(
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `BRAND` VARCHAR(255) NOT NULL,
    `MODEL` VARCHAR(255) NOT NULL,
    `STATUS` VARCHAR(255) NOT NULL,
    `PRICE` DECIMAL(5,2) NOT NULL,
    `CURRENCY` VARCHAR(255) NOT NULL,
    `YEAR` INT NOT NULL,
    `MILEAGE` INT,
    `FIRST_REGISTRATION` DATE,
    `VERSION` INT NOT NULL,
    `CREATED` DATE NOT NULL,
    `UPDATED` DATE,
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('FOR_SALE', 'ON_HOLD', 'NEW', 'SOLD')),
    CONSTRAINT CHK_CURRENCY CHECK (CURRENCY IN ('BGN', 'USD', 'EUR')),
    CONSTRAINT CHK_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CHK_YEAR CHECK (YEAR > 1900),
    CONSTRAINT CHK_MILEAGE CHECK (MILEAGE > 0)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `IMPORT_CAR_TASK` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `SOURCE` VARCHAR(1000) NOT NULL,
    `STATUS` VARCHAR (255) NOT NULL,
    `CAR_ID` BIGINT,
    `VERSION` INT NOT NULL,
    `CREATED` DATE NOT NULL,
    `UPDATED` DATE,
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('CREATED', 'PENDING', 'COMPLETED', 'FAILED')),
    FOREIGN KEY (CAR_ID) REFERENCES CAR(ID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `IMAGE` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `CAR_ID` BIGINT NOT NULL,
    `DATA` BLOB NOT NULL,
    `VERSION` INT NOT NULL,
    `CREATED` DATE NOT NULL,
    `UPDATED` DATE,
    FOREIGN KEY (CAR_ID) REFERENCES CAR(ID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

ALTER TABLE `IMPORT_CAR_TASK`
ADD (`ERROR` LONGTEXT);